Repository planetarium/9c-k8s-config, pull requests merged in 2022-11, with the labels that each got.

#62 add internal chain consistency test
  9c-internal/chain_test.py
  9c-internal/deploy-internal.sh
Labels: Extra Small

#63 [Data Provider] don't check tip when resetting snapshot
  9c-internal/configmap-data-provider.yaml
  9c-internal/data-provider.yaml
Labels: Extra Small

#69 [Fix] Update dotnet verion to 6.0.x
  .github/workflows/pytest.yaml
  .github/workflows/release.yaml
Labels: Extra Small

#65 Rc v100320
  .github/workflows/pytest.yaml
  .github/workflows/release.yaml
  9c-internal/configmap-versions.yaml
  9c-internal/kustomization.yaml
  9c-main/configmap-probe.yaml
  9c-main/deploy-main.sh
  9c-main/kube-system/coredns.yaml
  9c-main/miner-2.yaml
  9c-main/remote-headless-31.yaml
  9c-onboarding/sts-headless-query.yaml
  9c-onboarding/sts-headless-transfer.yaml
Labels: Small

#71 Rc v100321
  9c-internal/configmap-versions.yaml
  9c-internal/kustomization.yaml
  9c-main/configmap-versions.yaml
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-1.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/miner-4.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-10.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-6.yaml
  9c-main/remote-headless-7.yaml
  9c-main/remote-headless-8.yaml
  9c-main/remote-headless-9.yaml
  9c-main/remote-headless-99.yaml
  9c-main/snapshot-full.yaml
  9c-main/snapshot-partition-reset.yaml
  9c-main/snapshot-partition.yaml
  9c-onboarding/configmap-versions.yaml
  9c-onboarding/kustomization.yaml
Labels: Small

#68 Manual action and watch manifests
  .github/workflows/ snapshot-reset.yaml
  .github/workflows/prepare-release.yaml
  .github/workflows/release.yaml
  py-scripts/toolbelt/prepare/__init__.py
  py-scripts/toolbelt/prepare/manifest.py
  py-scripts/toolbelt/prepare/prepare.py
Labels: Large

#74 Rename actions
  .github/workflows/ snapshot-reset.yaml
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#75 Typo in miner-2.yaml
  9c-main/miner-2.yaml
Labels: Extra Small

#76 fix: Extract shell
  .github/workflows/release.yaml
Labels: Extra Small

#77 feat: Introduce specific commit release
  .github/workflows/prepare-release.yaml
  py-scripts/toolbelt/prepare/__init__.py
  py-scripts/toolbelt/prepare/prepare.py
  py-scripts/toolbelt/prepare/repos.py
Labels: Small

#79 feat: Apply specific release
  .github/workflows/prepare-release.yaml
  py-scripts/toolbelt/prepare/repos.py
Labels: Extra Small

#80 fix: Wrapping ""
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#81 fix typo
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#83 test commit
  9c-internal/deploy-internal.sh
Labels: Extra Small

#85 fix: extract, release condition
  .github/workflows/release.yaml
Labels: Extra Small

#87 fix: Add extract step id
  .github/workflows/release.yaml
Labels: Extra Small

#64 [Docs] Update README.md, CONTRIBUTING.md
  py-scripts/.env.sample
  py-scripts/CONTRIBUTING.md
  py-scripts/README.md
  py-scripts/pyproject.toml
Labels: Small

#91 Solved #73 Remove Unsigned prefix when os is linux or mac
  py-scripts/toolbelt/prepare/copy_machine.py
Labels: Extra Small

#92 Disable grafana chart `initChownData` feature
  9c-main/monitoring/grafana-values.yaml
Labels: bug, Extra Small, 9c-main/monitoring

#94 Add main release scripts
  .github/workflows/release.yaml
Labels: Extra Small

#95 [Fix] Remove cd ../
  .github/workflows/release.yaml
Labels: Extra Small

#96 fix: Rename snapshot reset action
  .github/workflows/snapshot-reset.yaml
Labels: No Changes

#99 update snapshot reset logic
  9c-internal/deploy-internal.sh
Labels: Extra Small

#101 [Feature] Update branch, tag naming rule
  .github/workflows/prepare-release.yaml
  py-scripts/tests/utils/test_parse.py
  py-scripts/toolbelt/prepare/__init__.py
  py-scripts/toolbelt/prepare/prepare.py
  py-scripts/toolbelt/utils/parse.py
Labels: Small

#104 migrate data provider to aurora
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
Labels: Extra Small

#102 Feature/docker image check
  .github/workflows/prepare-release.yaml
  py-scripts/cli.py
  py-scripts/tests/client/conftest.py
  py-scripts/tests/client/test_docker.py
  py-scripts/tests/testdata/client/docker/check_image_exists.json
  py-scripts/toolbelt/check/__init__.py
  py-scripts/toolbelt/check/image.py
  py-scripts/toolbelt/client/__init__.py
  py-scripts/toolbelt/client/docker.py
  py-scripts/toolbelt/prepare/prepare.py
  py-scripts/toolbelt/prepare/repos.py
Labels: Medium

#103 [Feature] Auto internal deploy tag
  py-scripts/toolbelt/prepare/prepare.py
Labels: Extra Small

#105 feat: Update prometheus log level to debug
  9c-main/monitoring/prometheus-values.yaml
Labels: bug, Extra Small, 9c-main/monitoring

#106 [Chore] Lint
  .github/workflows/check.yaml
  py-scripts/scripts/format.sh
  py-scripts/scripts/lint.sh
  py-scripts/toolbelt/check/__init__.py
  py-scripts/toolbelt/check/image.py
  py-scripts/toolbelt/client/aws.py
  py-scripts/toolbelt/k8s/manifest.py
  py-scripts/toolbelt/prepare/prepare.py
  py-scripts/toolbelt/prepare/repos.py
  py-scripts/toolbelt/update/release_infos.py
Labels: Small

#107 chore: Repo name var to const
  py-scripts/toolbelt/check/image.py
  py-scripts/toolbelt/constants.py
  py-scripts/toolbelt/prepare/prepare.py
Labels: Extra Small

#108 fix: Add working dir
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#109 fix: combine prepare release and check headless
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#111 chore: Handle http error (only logging)
  py-scripts/toolbelt/prepare/prepare.py
Labels: Extra Small

#114 feat: Change internal tag naming
  .github/workflows/prepare-release.yaml
  py-scripts/toolbelt/prepare/prepare.py
Labels: Extra Small

#112 reduce internal cluster setup time
  9c-internal/configmap-snapshot-script.yaml
  9c-internal/deploy-internal.sh
  9c-main/configmap-partition.yaml
Labels: Medium

#115 fix: Append key address, passphrase env
  .github/workflows/release.yaml
Labels: Extra Small

#116 feat: Update 9c-headless-metrics-aggregator log level to `trace`
  9c-main/monitoring/9c-headless-metrics-aggregator.yaml
Labels: Extra Small, 9c-main/monitoring

#117 feat: Update ninechronicles-headless-metrics-aggregator image
  9c-main/monitoring/9c-headless-metrics-aggregator.yaml
Labels: Extra Small

#119 test in ci-test branch
  README.md
Labels: Extra Small

#120 test
  README.md
Labels: Extra Small

#121 test
  README.md
Labels: Extra Small

#122 fix
  README.md
Labels: Extra Small

#123 test
  README.md
Labels: No Changes

#124 test
  README.md
Labels: Extra Small

#125 test
  README.md
Labels: Extra Small

#126 test
  README.md
Labels: No Changes

#128 Temp branch 4
  .github/workflows/release.yaml
  README.md
Labels: Extra Small

#127 feat: Limit requests timeout
  9c-main/monitoring/9c-headless-metrics-aggregator.yaml
Labels: Extra Small, 9c-main/monitoring

#129 test
  README.md
Labels: No Changes

#130 test
  README.md
Labels: No Changes

#133 [Fix] Release action if condition
  .github/workflows/release.yaml
Labels: Extra Small

#134 feat: Update headless version to v100321-4
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-99.yaml
Labels: Extra Small

#135 feat: Upgrade 9c-headless-metrics-aggregator
  9c-main/monitoring/9c-headless-metrics-aggregator.yaml
Labels: Extra Small

#138 Downgrade 2, 4 headless
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-4.yaml
Labels: Extra Small

#142 docs: Describe prometheus dashboard access tip
  9c-main/monitoring/README.md
Labels: Extra Small

#143 add liveness probe for miners
  9c-main/miner-1.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/miner-4.yaml
Labels: Extra Small

#148 Increase launcher project version
  9c-main/configmap-versions.yaml
Labels: Extra Small

#149 update to the latest config
  9c-main/deploy-main.sh
  9c-main/remote-headless-10.yaml
  9c-main/remote-headless-6.yaml
  9c-main/remote-headless-7.yaml
  9c-main/remote-headless-8.yaml
  9c-main/remote-headless-9.yaml
  9c-main/seed-deployment-1.yaml
  9c-main/seed-deployment-2.yaml
  9c-main/seed-deployment-3.yaml
  9c-onboarding/configmap-versions.yaml
Labels: Extra Large

#150 [Fix] Sync manifest files
  py-scripts/toolbelt/prepare/manifest.py
Labels: Extra Small

#152 fix script
  9c-internal/chain_test.py
  9c-main/configmap-full.yaml
Labels: Extra Small
