Repository planetarium/9c-k8s-config, pull requests merged in 2022-10, with the labels that each got.

#15 fix image tag
  9c-main/remote-headless-4.yaml
Labels: Extra Small

#17 [Feature] test mode
  9c-main/configmap-versions.yaml
  py-scripts/.vscode/launch.json
  py-scripts/cli.py
  py-scripts/tests/client/conftest.py
  py-scripts/tests/client/test_slack.py
  py-scripts/tests/github/__init__.py
  py-scripts/tests/github/test_parser.py
  py-scripts/tests/planet/test_generator.py
  py-scripts/tests/planet/test_planet.py
  py-scripts/tests/test_config.py
  py-scripts/toolbelt/client/__init__.py
  py-scripts/toolbelt/client/github.py
  py-scripts/toolbelt/client/session.py
  py-scripts/toolbelt/config.py
  py-scripts/toolbelt/constants.py
  py-scripts/toolbelt/exceptions.py
  py-scripts/toolbelt/github/commit.py
  py-scripts/toolbelt/github/github_commit_url.py
  py-scripts/toolbelt/github/old_github.py
  py-scripts/toolbelt/github/parser.py
  py-scripts/toolbelt/github/release_9c_repos.py
  py-scripts/toolbelt/k8s/__init__.py
  py-scripts/toolbelt/k8s/apv.py
  py-scripts/toolbelt/k8s/update.py
  py-scripts/toolbelt/k8s_update/__init__.py
  py-scripts/toolbelt/k8s_update/update.py
  py-scripts/toolbelt/k8s_update/update_internal_yamls.py
  py-scripts/toolbelt/k8s_update/update_k8s_yaml.py
  py-scripts/toolbelt/planet/__init__.py
  py-scripts/toolbelt/planet/planet.py
  py-scripts/toolbelt/prepare/__init__.py
  py-scripts/toolbelt/prepare/copy_machine.py
  py-scripts/toolbelt/prepare/prepare.py
  py-scripts/toolbelt/prepare/prepare_main_deploy.py
  py-scripts/toolbelt/types.py
  py-scripts/toolbelt/update/__init__.py
  py-scripts/toolbelt/update/post_deploy.py
  py-scripts/toolbelt/utils/__init__.py
  py-scripts/toolbelt/utils/typer.py
  py-scripts/toolbelt/utils/url.py
  py-scripts/toolbelt/v2/__init__.py
  py-scripts/toolbelt/v2/artifacts/launcher.py
  py-scripts/toolbelt/v2/artifacts/player.py
  py-scripts/toolbelt/v2/command.py
  py-scripts/toolbelt/v2/planet/apv.py
  py-scripts/toolbelt/v2/types.py
  py-scripts/toolbelt/validators/validate.py
Labels: Extra Large

#20 fix: Select tuple
  py-scripts/toolbelt/k8s/update.py
  py-scripts/toolbelt/prepare/__init__.py
Labels: Extra Small

#21 Introduce configmap in 9c-main
  .github/bin/check_apv_consistency.py
  .github/bin/requirements.txt
  .github/workflows/check.yaml
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/deploy-main.sh
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-1.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/miner-4.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-10.yaml
  9c-main/remote-headless-11.yaml
  9c-main/remote-headless-12.yaml
  9c-main/remote-headless-13.yaml
  9c-main/remote-headless-14.yaml
  9c-main/remote-headless-15.yaml
  9c-main/remote-headless-16.yaml
  9c-main/remote-headless-17.yaml
  9c-main/remote-headless-18.yaml
  9c-main/remote-headless-19.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-20.yaml
  9c-main/remote-headless-21.yaml
  9c-main/remote-headless-22.yaml
  9c-main/remote-headless-23.yaml
  9c-main/remote-headless-24.yaml
  9c-main/remote-headless-25.yaml
  9c-main/remote-headless-26.yaml
  9c-main/remote-headless-27.yaml
  9c-main/remote-headless-28.yaml
  9c-main/remote-headless-29.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-30.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-6.yaml
  9c-main/remote-headless-7.yaml
  9c-main/remote-headless-8.yaml
  9c-main/remote-headless-9.yaml
  9c-main/remote-headless-99.yaml
  9c-main/seed-deployment-1.yaml
  9c-main/seed-deployment-2.yaml
  9c-main/seed-deployment-3.yaml
  9c-main/snapshot-full.yaml
  9c-main/snapshot-partition-reset.yaml
  9c-main/snapshot-partition.yaml
  9c-main/tcp-seed-deployment-1.yaml
  9c-main/tcp-seed-deployment-2.yaml
  9c-main/tcp-seed-deployment-3.yaml
Labels: Extra Large

#24 Add pytest action
  .github/workflows/pytest.yaml
Labels: Extra Small

#25 Restore pytest action
  .github/workflows/pytest.yaml
Labels: Extra Small

#27 Add pytest action
  .github/workflows/pytest.yaml
Labels: Extra Small

#28 [Chore] Remove coverage fail option
  py-scripts/pyproject.toml
Labels: Extra Small

#29 [Chore] Rename auto reviewer
  .github/auto_assign.yml
Labels: No Changes

#32 [Feature] Add release action
  .github/workflows/release.yaml
Labels: Extra Small

#33 [Chore] Release concurrency
  .github/workflows/release.yaml
Labels: Extra Small

#34 Test rc v100302
  .github/workflows/release.yaml
  9c-internal/configmap-versions.yaml
  9c-internal/kustomization.yaml
Labels: Extra Small

#35 [Chore] Remove test mode
  .github/workflows/release.yaml
Labels: Extra Small

#36 RC v100302
  .github/workflows/release.yaml
  9c-internal/configmap-versions.yaml
Labels: Extra Small

#38 Update mainnet configuration for `v100310` prep
  9c-main/configmap-probe.yaml
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-10.yaml
  9c-main/remote-headless-11.yaml
  9c-main/remote-headless-12.yaml
  9c-main/remote-headless-13.yaml
  9c-main/remote-headless-14.yaml
  9c-main/remote-headless-15.yaml
  9c-main/remote-headless-16.yaml
  9c-main/remote-headless-17.yaml
  9c-main/remote-headless-18.yaml
  9c-main/remote-headless-19.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-20.yaml
  9c-main/remote-headless-21.yaml
  9c-main/remote-headless-22.yaml
  9c-main/remote-headless-23.yaml
  9c-main/remote-headless-24.yaml
  9c-main/remote-headless-25.yaml
  9c-main/remote-headless-26.yaml
  9c-main/remote-headless-27.yaml
  9c-main/remote-headless-28.yaml
  9c-main/remote-headless-29.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-30.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-6.yaml
  9c-main/remote-headless-7.yaml
  9c-main/remote-headless-8.yaml
  9c-main/remote-headless-9.yaml
  9c-main/remote-headless-99.yaml
Labels: Extra Large

#41 [Refactor] replace old GitHub
  py-scripts/tests/client/conftest.py
  py-scripts/tests/client/test_github.py
  py-scripts/tests/github/__init__.py
  py-scripts/tests/k8s/test_manifest.py
  py-scripts/tests/testdata/client/github/path_content.json
  py-scripts/tests/testdata/client/github/update_content.json
  py-scripts/tests/utils/test_parse.py
  py-scripts/toolbelt/client/github.py
  py-scripts/toolbelt/github/__init__.py
  py-scripts/toolbelt/github/commit.py
  py-scripts/toolbelt/github/old_github.py
  py-scripts/toolbelt/k8s/__init__.py
  py-scripts/toolbelt/k8s/manifest.py
  py-scripts/toolbelt/prepare/manifest.py
  py-scripts/toolbelt/prepare/prepare.py
  py-scripts/toolbelt/utils/parse.py
  py-scripts/toolbelt/validators/__init__.py
  py-scripts/toolbelt/validators/apv.py
  py-scripts/toolbelt/validators/validate.py
  py-scripts/toolbelt/validators/validate_docker.py
Labels: Extra Large

#42 [Feat] Handle all manifests
  py-scripts/tests/k8s/test_manifest.py
  py-scripts/tests/testdata/k8s/configmap-versions/result-configmap-versions.yaml
  py-scripts/tests/testdata/k8s/explorer/explorer.yaml
  py-scripts/tests/testdata/k8s/explorer/result-explorer.yaml
  py-scripts/tests/testdata/k8s/miner-1/miner-1.yaml
  py-scripts/tests/testdata/k8s/miner-1/result-miner-1.yaml
  py-scripts/tests/testdata/k8s/remote-headless-1/remote-headless-1.yaml
  py-scripts/tests/testdata/k8s/remote-headless-1/result-remote-headless-1.yaml
  py-scripts/tests/testdata/k8s/snapshot-full/result-snapshot-full.yaml
  py-scripts/tests/testdata/k8s/snapshot-full/snapshot-full.yaml
  py-scripts/tests/testdata/k8s/snapshot-partition-reset/result-snapshot-partition-reset.yaml
  py-scripts/tests/testdata/k8s/snapshot-partition-reset/snapshot-partition-reset.yaml
  py-scripts/tests/testdata/k8s/snapshot-partition/result-snapshot-partition.yaml
  py-scripts/tests/testdata/k8s/snapshot-partition/snapshot-partition.yaml
  py-scripts/toolbelt/k8s/manifest.py
  py-scripts/toolbelt/prepare/manifest.py
  py-scripts/toolbelt/prepare/prepare.py
Labels: Extra Large

#43 Change to `get last commit` from branch
  .github/workflows/release.yaml
  py-scripts/tests/client/conftest.py
  py-scripts/tests/client/test_github.py
  py-scripts/tests/k8s/test_manifest.py
  py-scripts/tests/testdata/client/github/create_pull.json
  py-scripts/tests/testdata/client/github/create_ref.json
  py-scripts/tests/testdata/client/github/get_ref.json
  py-scripts/tests/testdata/k8s/full-state/full-state.yaml
  py-scripts/tests/testdata/k8s/full-state/result-full-state.yaml
  py-scripts/toolbelt/client/github.py
  py-scripts/toolbelt/k8s/manifest.py
  py-scripts/toolbelt/prepare/manifest.py
  py-scripts/toolbelt/prepare/prepare.py
  py-scripts/toolbelt/prepare/repos.py
  py-scripts/toolbelt/types.py
Labels: Extra Large

#47 Update 9c-main miner host
  9c-main/monitoring/9c-headless-metrics-aggregator.yaml
Labels: Extra Small

#48 [Feature] Handle seed, dp manifests
  py-scripts/scripts/format.sh
  py-scripts/tests/k8s/test_manifest.py
  py-scripts/tests/testdata/k8s/data-provider-db/data-provider-db.yaml
  py-scripts/tests/testdata/k8s/data-provider-db/result-data-provider-db.yaml
  py-scripts/tests/testdata/k8s/data-provider/data-provider.yaml
  py-scripts/tests/testdata/k8s/data-provider/result-data-provider.yaml
  py-scripts/tests/testdata/k8s/full-state/result-full-state.yaml
  py-scripts/tests/testdata/k8s/kustomization/result-kustomization.yaml
  py-scripts/tests/testdata/k8s/miner-1/result-miner-1.yaml
  py-scripts/tests/testdata/k8s/seed-deployment-1/result-seed-deployment-1.yaml
  py-scripts/tests/testdata/k8s/seed-deployment-1/seed-deployment-1.yaml
  py-scripts/tests/testdata/k8s/snapshot-full/result-snapshot-full.yaml
  py-scripts/tests/testdata/k8s/snapshot-partition-reset/result-snapshot-partition-reset.yaml
  py-scripts/tests/testdata/k8s/snapshot-partition/result-snapshot-partition.yaml
  py-scripts/tests/testdata/k8s/tcp-seed-deployment-1/result-tcp-seed-deployment-1.yaml
  py-scripts/tests/testdata/k8s/tcp-seed-deployment-1/tcp-seed-deployment-1.yaml
  py-scripts/toolbelt/constants.py
  py-scripts/toolbelt/k8s/manifest.py
  py-scripts/toolbelt/prepare/manifest.py
  py-scripts/toolbelt/prepare/repos.py
Labels: Extra Large

#49 [Fix] store dir name
  py-scripts/tests/client/conftest.py
  py-scripts/tests/client/test_github.py
  py-scripts/tests/k8s/test_manifest.py
  py-scripts/toolbelt/client/github.py
  py-scripts/toolbelt/k8s/manifest.py
  py-scripts/toolbelt/prepare/copy_machine.py
  py-scripts/toolbelt/prepare/manifest.py
  py-scripts/toolbelt/prepare/prepare.py
  py-scripts/toolbelt/prepare/repos.py
  py-scripts/toolbelt/types.py
Labels: Medium

#50 [Refactor] Post deploy
  py-scripts/cli.py
  py-scripts/toolbelt/client/aws.py
  py-scripts/toolbelt/planet/planet.py
  py-scripts/toolbelt/prepare/copy_machine.py
  py-scripts/toolbelt/update/__init__.py
  py-scripts/toolbelt/update/post_deploy.py
  py-scripts/toolbelt/update/release_infos.py
  py-scripts/toolbelt/utils/url.py
Labels: Medium

#51 [Chore] Apply update release info script in CD
  .github/workflows/release.yaml
Labels: Extra Small

#53 update v100310 to latest
  9c-main/configmap-full.yaml
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-1.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/miner-4.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-10.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-6.yaml
  9c-main/remote-headless-7.yaml
  9c-main/remote-headless-8.yaml
  9c-main/remote-headless-9.yaml
  9c-main/remote-headless-99.yaml
  9c-main/snapshot-full.yaml
  9c-main/snapshot-partition-reset.yaml
  9c-main/snapshot-partition.yaml
  9c-onboarding/kustomization.yaml
Labels: Small

#54 Fix DP configuration before `v100311` hotfix
  9c-main/data-provider-db.yaml
Labels: Extra Small

#56 Update rc v100311 manifests 1666771099
  9c-main/configmap-versions.yaml
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-1.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/miner-4.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-10.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-6.yaml
  9c-main/remote-headless-7.yaml
  9c-main/remote-headless-8.yaml
  9c-main/remote-headless-9.yaml
  9c-main/remote-headless-99.yaml
  9c-main/snapshot-full.yaml
  9c-main/snapshot-partition-reset.yaml
  9c-main/snapshot-partition.yaml
  9c-onboarding/configmap-versions.yaml
  9c-onboarding/kustomization.yaml
Labels: Small

#55 RC v100311
  .github/workflows/release.yaml
  9c-main/configmap-versions.yaml
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-1.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/miner-4.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-10.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-6.yaml
  9c-main/remote-headless-7.yaml
  9c-main/remote-headless-8.yaml
  9c-main/remote-headless-9.yaml
  9c-main/remote-headless-99.yaml
  9c-main/snapshot-full.yaml
  9c-main/snapshot-partition-reset.yaml
  9c-main/snapshot-partition.yaml
  9c-onboarding/configmap-versions.yaml
  9c-onboarding/kustomization.yaml
  py-scripts/tests/k8s/test_manifest.py
  py-scripts/toolbelt/k8s/manifest.py
  py-scripts/toolbelt/prepare/repos.py
Labels: Small

#60 Switch active-standby miner
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
Labels: Extra Small

#58 delete seed nodes before deployment
  9c-main/deploy-main.sh
Labels: Extra Small

#61 delete seed nodes before deployment
  9c-main/deploy-main.sh
Labels: Extra Small
