Repository planetarium/9c-k8s-config, pull requests merged in 2022-12, with the labels that each got.

#163 Introduce codesign action
  .github/workflows/prepare-release.yaml
  py-scripts/.gitignore
  py-scripts/toolbelt/constants.py
  py-scripts/toolbelt/prepare/__init__.py
  py-scripts/toolbelt/prepare/copy_machine.py
Labels: Small

#174 Update prepare-release.yaml
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#178 [9c-internal] increase snapshot schedule
  9c-internal/snapshot.yaml
Labels: Extra Small

#186 fix: Rollback artifact os types
  py-scripts/toolbelt/prepare/copy_machine.py
Labels: Extra Small

#188 chore: Boolean choice option
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#190 fix: Sign condition
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#193 Add sentry options to internal args
  9c-internal/miner-1.yaml
  9c-internal/remote-headless-1.yaml
Labels: Extra Small

#199 add sentry options to mainnet
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-99.yaml
Labels: Extra Small

#200 Remove 9c-test bucket url
  9c-test/data-provider.yaml
  9c-test/miner-1.yaml
  9c-test/remote-headless-1.yaml
  9c-test/remote-headless-2.yaml
Labels: Extra Small

#201 9c-release -> drfoj4ogb5dwf
  9c-test/data-provider.yaml
  9c-test/miner-1.yaml
  9c-test/remote-headless-1.yaml
  9c-test/remote-headless-2.yaml
Labels: Extra Small

#202 fix: Remove copy to test bucket funcs
  py-scripts/toolbelt/update/__init__.py
  py-scripts/toolbelt/update/release_infos.py
Labels: Extra Small

#204 update genesis block path in DP configuration
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
Labels: Extra Small

#205 bump 9c-headless-aggregator
  9c-main/monitoring/9c-headless-metrics-aggregator.yaml
Labels: Extra Small

#206 update to latest configuration
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/kube-system/coredns.yaml
  9c-main/rpc-client-lite.yaml
Labels: Extra Small

#194 Reset internal dataprovider db
  9c-internal/configmap-data-provider.yaml
  9c-internal/data-provider.yaml
  9c-internal/deploy-internal.sh
  9c-internal/test-deploy-internal.sh
Labels: Medium

#211 fix: Replace rstrip -> removesuffix
  py-scripts/toolbelt/prepare/copy_machine.py
Labels: Extra Small
