Repository planetarium/9c-k8s-config, pull requests merged in 2023-02, with the labels that each got.

#255 remove `worker` option for v100360 prep
  9c-main/configmap-full.yaml
  9c-main/configmap-partition-reset.yaml
  9c-main/configmap-partition.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-1.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/miner-4.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-99.yaml
  9c-main/tcp-seed-deployment-1.yaml
  9c-main/tcp-seed-deployment-2.yaml
  9c-main/tcp-seed-deployment-3.yaml
Labels: Extra Small

#260 update internal config to latest
  9c-internal/data-provider.yaml
  9c-internal/explorer.yaml
  9c-internal/miner-1.yaml
  9c-internal/miner-2.yaml
  9c-internal/remote-headless-1.yaml
  9c-internal/service.yaml
Labels: Medium

#261 remove replace snapshot partition reset
  py-scripts/tests/k8s/test_manifest.py
  py-scripts/tests/testdata/k8s/snapshot-partition-reset/result-snapshot-partition-reset.yaml
  py-scripts/tests/testdata/k8s/snapshot-partition-reset/snapshot-partition-reset.yaml
  py-scripts/toolbelt/k8s/manifest.py
  py-scripts/toolbelt/prepare/manifest.py
Labels: Extra Large

#263 [9c-onboarding] remove workers
  9c-onboarding/sts-headless-query.yaml
  9c-onboarding/sts-headless-transfer.yaml
Labels: Extra Small

#264 [9c-main] update config
  9c-main/configmap-partition.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
Labels: Extra Small

#265 remove headless 99
  py-scripts/toolbelt/prepare/manifest.py
Labels: Extra Small

#267 update rpc image
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
Labels: Extra Small

#258 Update config settings for `pbft-internal`
  9c-pbft-internal/configmap-snapshot-script.yaml
  9c-pbft-internal/explorer.yaml
  9c-pbft-internal/kustomization.yaml
  9c-pbft-internal/miner-1.yaml
  9c-pbft-internal/remote-headless-1.yaml
  9c-pbft-internal/seed-pow.yaml
  9c-pbft-internal/seed.yaml
  9c-pbft-internal/service.yaml
  9c-pbft-internal/snapshot-pvc.yaml
  9c-pbft-internal/snapshot.yaml
  9c-pbft-internal/validator-1.yaml
  9c-pbft-internal/validator-2.yaml
  9c-pbft-internal/validator-3.yaml
  9c-pbft-internal/validator-4.yaml
Labels: Large

#271 [9c-main] Update latest v100360 config
  9c-main/bridge-status-bot.yaml
  9c-main/monitoring/9c-headless-metrics-aggregator.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/snapshot-full.yaml
  9c-main/snapshot-partition-reset.yaml
  9c-main/snapshot-partition.yaml
Labels: Extra Small

#272 remove dp deployment due to maintenance
  9c-main/deploy-main.sh
Labels: Extra Small

#273 comment out onboarding deployment for hotfix
  9c-main/deploy-main.sh
Labels: Extra Small

#269 Fix app protocol version on configmap-versions
  9c-pbft-internal/configmap-versions.yaml
  9c-pbft-internal/headless-admin.yaml
  9c-pbft-internal/service.yaml
Labels: Medium

#275 [9c main] v100361 config
  9c-main/data-provider-db.yaml
  9c-main/deploy-main.sh
  9c-main/miner-2.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
Labels: Extra Small

#276 Append log to s3 conf
  9c-main/cwagent-fluent-bit.yaml
Labels: Small

#277 Fix fluent bit cwl config
  9c-main/cwagent-fluent-bit.yaml
Labels: Medium

#280 reduce tx lifetime to 10 min
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-onboarding/sts-headless-query.yaml
  9c-onboarding/sts-headless-transfer.yaml
Labels: Extra Small

#282 update to latest config
  9c-main/data-provider-db.yaml
  9c-main/monitoring/9c-headless-metrics-aggregator.yaml
Labels: Extra Small

#284 fix script to minimize store error
  9c-internal/configmap-snapshot-script.yaml
Labels: Extra Small

#285 update snapshot schedule
  9c-main/snapshot-full.yaml
  9c-main/snapshot-partition-reset.yaml
  9c-main/snapshot-partition.yaml
Labels: Extra Small

#286 fix checking complete log
  9c-main/configmap-full.yaml
  9c-main/configmap-partition-reset.yaml
  9c-main/configmap-partition.yaml
Labels: Extra Small

#287 Update snapshot config
  9c-main/configmap-full.yaml
  9c-main/configmap-partition-reset.yaml
  9c-main/configmap-partition.yaml
  9c-main/snapshot-full.yaml
  9c-main/snapshot-partition-reset.yaml
  9c-main/snapshot-partition.yaml
Labels: Extra Small
