Repository planetarium/9c-k8s-config, pull requests merged in 2023-01, with the labels that each got.

#212 update trusted apv signer
  9c-main/configmap-full.yaml
  9c-main/configmap-partition-reset.yaml
  9c-main/configmap-partition.yaml
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-1.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/miner-4.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-99.yaml
  9c-onboarding/sts-headless-query.yaml
  9c-onboarding/sts-headless-transfer.yaml
  py-scripts/tests/testdata/k8s/explorer/explorer.yaml
  py-scripts/tests/testdata/k8s/explorer/result-explorer.yaml
  py-scripts/tests/testdata/k8s/full-state/full-state.yaml
  py-scripts/tests/testdata/k8s/full-state/result-full-state.yaml
  py-scripts/tests/testdata/k8s/miner-1/miner-1.yaml
  py-scripts/tests/testdata/k8s/miner-1/result-miner-1.yaml
  py-scripts/tests/testdata/k8s/remote-headless-1/remote-headless-1.yaml
  py-scripts/tests/testdata/k8s/remote-headless-1/result-remote-headless-1.yaml
Labels: Small

#214 update apv
  9c-main/configmap-versions.yaml
  9c-onboarding/configmap-versions.yaml
Labels: Extra Small

#215 Change image for subject headless test
  9c-main/remote-headless-31.yaml
Labels: Extra Small

#153 Introduce 9c-pbft-internal
  9c-main/deploy-main.sh
  9c-pbft-internal/configmap-data-provider.yaml
  9c-pbft-internal/configmap-snapshot-script.yaml
  9c-pbft-internal/configmap-versions.yaml
  9c-pbft-internal/data-provider-db.yaml
  9c-pbft-internal/data-provider.yaml
  9c-pbft-internal/deploy-internal.sh
  9c-pbft-internal/download-snapshot.sh
  9c-pbft-internal/explorer.yaml
  9c-pbft-internal/gp2-extensible.yaml
  9c-pbft-internal/kustomization.yaml
  9c-pbft-internal/miner-1.yaml
  9c-pbft-internal/remote-headless-1.yaml
  9c-pbft-internal/secret.yaml
  9c-pbft-internal/service.yaml
  9c-pbft-internal/snapshot-pvc.yaml
  9c-pbft-internal/snapshot.yaml
  9c-pbft-internal/tcp-seed-deployment.yaml
  9c-pbft-internal/test-deploy-internal.sh
  9c-pbft-internal/tx-repeater.yaml
  9c-pbft-internal/validator-1.yaml
  9c-pbft-internal/validator-10.yaml
  9c-pbft-internal/validator-11.yaml
  9c-pbft-internal/validator-12.yaml
  9c-pbft-internal/validator-2.yaml
  9c-pbft-internal/validator-3.yaml
  9c-pbft-internal/validator-4.yaml
  9c-pbft-internal/validator-5.yaml
  9c-pbft-internal/validator-6.yaml
  9c-pbft-internal/validator-7.yaml
  9c-pbft-internal/validator-8.yaml
  9c-pbft-internal/validator-9.yaml
Labels: Extra Large

#207 Introduce world boss service pods
  9c-onboarding/world-boss-service.yaml
  9c-onboarding/world-boss-worker.yaml
Labels: Medium

#217 update nodegroups
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-3.yaml
  9c-main/tcp-seed-deployment-1.yaml
  9c-main/tcp-seed-deployment-2.yaml
  9c-main/tcp-seed-deployment-3.yaml
  9c-onboarding/sts-headless-query.yaml
Labels: Extra Small

#218 [Fix] Rollback wait pod script
  9c-main/deploy-main.sh
Labels: Extra Small

#219 use aria2c instead of wget
  9c-internal/configmap-snapshot-script.yaml
Labels: Extra Small

#220 Update mainnet configuration to latest
  9c-main/configmap-probe.yaml
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-2.yaml
  9c-main/miner-3.yaml
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-99.yaml
  9c-onboarding/sts-headless-query.yaml
  9c-onboarding/sts-headless-transfer.yaml
Labels: Small

#222 chore: Remove headless signing
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#221 Update miner livenessprobe
  9c-main/configmap-probe.yaml
  9c-main/miner-2.yaml
  9c-main/snapshot-partition.yaml
Labels: Extra Small

#225 Parallelize reset snapshots with xargs
  9c-internal/deploy-internal.sh
Labels: Extra Small, deploy-script

#224 fix internal configuration
  9c-internal/configmap-data-provider.yaml
  9c-internal/configmap-snapshot-script.yaml
  9c-internal/data-provider.yaml
Labels: Extra Small

#226 fix aria2c option test
  9c-internal/configmap-snapshot-script.yaml
Labels: Extra Small

#229 update internal config
  9c-internal/configmap-snapshot-script.yaml
  9c-internal/data-provider.yaml
  9c-internal/explorer.yaml
  9c-internal/miner-1.yaml
  9c-internal/miner-2.yaml
  9c-internal/remote-headless-1.yaml
  9c-internal/snapshot.yaml
Labels: Extra Small

#230 [9c-internal] change gp2 to gp3
  9c-internal/data-provider-db.yaml
  9c-internal/onboarding-db.yaml
Labels: Extra Small

#233 clean up service
  9c-internal/deploy-internal.sh
  9c-internal/kustomization.yaml
  9c-internal/onboarding-app.yaml
  9c-internal/onboarding-db.yaml
  9c-internal/onboarding-redis.yaml
  9c-internal/snapshot.yaml
Labels: Large

#236 fix: Remove slack token in internal
  9c-internal/configmap-snapshot-script.yaml
  9c-internal/deploy-internal.sh
Labels: Extra Small

#237 Scrape metrics more often
  9c-main/monitoring/prometheus-values.yaml
Labels: Extra Small, 9c-main/monitoring

#238 update config
  9c-main/service.yaml
  9c-main/tcp-seed-deployment-1.yaml
  9c-main/tcp-seed-deployment-2.yaml
  9c-main/tcp-seed-deployment-3.yaml
Labels: Extra Large

#239 9c main/update storageclass
  9c-main/data-provider-db.yaml
  9c-main/data-provider.yaml
  9c-main/explorer.yaml
  9c-main/full-state.yaml
  9c-main/miner-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-99.yaml
Labels: Extra Small

#240 [9c-onboarding] Update instance types
  9c-onboarding/sts-headless-query.yaml
  9c-onboarding/sts-headless-transfer.yaml
  9c-onboarding/world-boss-service.yaml
  9c-onboarding/world-boss-worker.yaml
Labels: Extra Small

#241 Fix internal snapshot script
  9c-internal/configmap-snapshot-script.yaml
Labels: Extra Small

#243 fix parsing error
  9c-internal/deploy-internal.sh
Labels: Extra Small

#244 update slack webhook configuration
  9c-internal/configmap-snapshot-script.yaml
  9c-internal/data-provider-db.yaml
  9c-internal/data-provider.yaml
  9c-internal/explorer.yaml
  9c-internal/kustomization.yaml
  9c-internal/miner-1.yaml
  9c-internal/miner-2.yaml
  9c-internal/remote-headless-1.yaml
  9c-internal/snapshot.yaml
Labels: Extra Small

#245 fix script variables
  9c-internal/configmap-snapshot-script.yaml
Labels: Extra Small

#246 fix script variables
  9c-internal/configmap-snapshot-script.yaml
Labels: Extra Small

#249 update to latest snapshot configuration
  9c-internal/configmap-snapshot-script.yaml
  9c-internal/kustomization.yaml
  9c-main/configmap-full.yaml
  9c-main/configmap-partition.yaml
  9c-main/snapshot-full.yaml
  9c-main/snapshot-partition.yaml
Labels: Extra Small

#250 update snapshot config
  9c-internal/kustomization.yaml
  9c-main/configmap-partition-reset.yaml
  9c-main/snapshot-full.yaml
  9c-main/snapshot-partition-reset.yaml
  9c-main/snapshot-partition.yaml
Labels: Small

#251 increase sentry trace sample rate
  9c-main/remote-headless-1.yaml
  9c-main/remote-headless-2.yaml
  9c-main/remote-headless-3.yaml
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-4.yaml
  9c-main/remote-headless-5.yaml
  9c-main/remote-headless-99.yaml
Labels: Extra Small

#254 update config
  9c-main/remote-headless-31.yaml
  9c-main/remote-headless-99.yaml
  9c-onboarding/sts-headless-transfer.yaml
Labels: Extra Small
